Eshop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Migrations;
using PagedList;
using System.Net.Mail;
using System.Net;
using System.Data.Entity;
using Eshop.ViewModels;



namespace Eshop.Controllers
{
    public class CartController : Controller
    {
        private readonly Entities db;
        public CartController()
        {
            db = new Entities();
        }
        // GET: Cart
        public ActionResult Index()
        {
            if(!this.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login","User");
            }
            var userId = 0;
            if (User.Identity.Name != "")
            {
                userId = db.Users.SingleOrDefault(u => u.Email == User.Identity.Name).UserId;
            }
            var cart = db.carts.Where(u => u.userId == userId).ToList();
            var total = db.carts
                .Where(p => p.userId == userId)
                .Select(p => p.product.price * p.quantity)
                .Sum() ?? 0;

            var thisUser = db.Users.SingleOrDefault(x => x.Email == this.User.Identity.Name);  // Allagh JJJ
            var desktopPrice = db.carts.
                Where(x => x.userId == userId).
                Select(y => y.Desktop.price)
                .Sum() ?? 0;
                


       
            var TotalPrice = total + desktopPrice;

            TempData["total"] = TotalPrice;                                                     // Allagh JJJ
            TempData["productsInCart"] = db.carts.Where(u => u.userId == userId).Count();
            return View(cart);
        }

        [HttpPost]
        public ActionResult AddToCartProduct(int id)
        {
            var userId = 0;
            if (User.Identity.Name != "")
            {
                userId = db.Users.SingleOrDefault(u => u.Email == User.Identity.Name).UserId;
            }

            var products = new cart()
            {
                quantity = 1,
                userId = (int)userId,
                productId = id
            };

            if (db.carts.Any(p => p.productId == id && p.userId == userId))
                return Json(new { status = "Product already added to cart" },JsonRequestBehavior.AllowGet);

            db.carts.Add(products);
            db.SaveChanges();

            return Json(new { status = "Added to Cart!" }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult AddDesktopToCart()
        {
            var userId = 0;
            if (User.Identity.Name != "")
            {
                userId = db.Users.SingleOrDefault(u => u.Email == User.Identity.Name).UserId;
            }
            var thisUser = db.Users.SingleOrDefault(x => x.Email == this.User.Identity.Name);

            var products = new cart()
            {
                quantity = 1,
                userId = (int)userId,
                desktopID = thisUser.MyDesktop
            };

            db.carts.Add(products);
            db.SaveChanges();

            return Json(new { status = "Added to Cart!" }, JsonRequestBehavior.AllowGet);

        }

        [HttpDelete]
        public void RemoveProductFromCart(int id)
        {
            var userId = 0;
            if (User.Identity.Name != "")
            {
                userId = db.Users.SingleOrDefault(u => u.Email == User.Identity.Name).UserId;
            }
          
            var cartInDb = db.carts.SingleOrDefault(c => c.Id == id && c.userId == userId);
            db.carts.Remove(cartInDb);
            db.SaveChanges();
        }

        public JsonResult UpdateCart(int prod_id, int prod_qty)
        {
            var userId = 0;
            if (User.Identity.Name != "")
            {
                userId = db.Users.SingleOrDefault(u => u.Email == User.Identity.Name).UserId;
            }
            var updateCart =
                db.carts.SingleOrDefault
                (p => p.userId == userId && p.productId == prod_id);

            updateCart.quantity = prod_qty;


            db.carts.AddOrUpdate(updateCart);
            db.SaveChanges();

            return Json(new { productId = prod_id, productQuantity = prod_qty }, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eshop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eshop;
using Eshop.ViewModels;

namespace Eshop.Controllers
{

    public class OrdersController : Controller
    {
       
        private Entities db;
        public OrdersController()
        {
            db = new Entities();
        }

        public ActionResult MyOrders()
        {
            var userId = 0;
            if (User.Identity.Name != "")
            {
                userId = db.Users.SingleOrDefault(u => u.Email == User.Identity.Name).UserId;
            }
            var orders = db.orders.Where(u => u.userId == userId).ToList();
            
            TempData["productsInCart"] = db.carts.Where(x => x.userId == userId).Count();

            return View(orders);
        }

        public ActionResult MyOrder(int orderId)
        {
            var userId = 0;
            if (User.Identity.Name != "")
                userId = db.Users.SingleOrDefault(u => u.Email == User.Identity.Name).UserId;

            var myOrder = db.orders.SingleOrDefault(o => o.id == orderId);
            TempData["productsInCart"] = db.carts.Where(u => u.userId == userId).Count();
            return View("MyOrder", myOrder);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eshop/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/c93712fc6c.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Admin/css")
</head>
<body>

    <div class="page-wrapper">
        <div class="admin-sidebar">
            <div class="admin-sidebar-logo">
                <a href="@Url.Content("/")">
                    <h3>
                        C
                        <span>YBERSTORE</span>
                    </h3>
                </a>
            </div>
            <ul>
                <li class="navigation-header">@Html.ActionLink("Dashboard", "Index", "Admin", new { }, new { @class = "product-create-link" })</li>
                <li>
            </ul>
            <div data-tab="1" class="sub-header arrow-down">
                <div class="icon-container">
                    <img class="icon" src="~/Images/Admin/tower.png" alt="">
                </div>

                <div class="sub-header-2">
                    Box
                    <i class="fas fa-angle-down"></i>
                </div>
            </div>

            <ul class="dropdown dropdown--1 ">
                <li>
                    @Html.ActionLink("Insert Box", "InsertProduct", "Admin", new { id = 9 }, new { @class = "product-create-link" })
                </li>
            </ul>
            <div data-tab="8" class="sub-header arrow-down">
                <div class="icon-container">
                    <img class="icon" src="~/Images/Admin/monitor.png" alt="">
                </div>

                <div class="sub-header-2">
                    Monitor
                    <i class="fas fa-angle-down"></i>
                </div>
            </div>

            <ul class="dropdown dropdown--8 ">
                <li>
                    @Html.ActionLink("Insert Monitor", "InsertProduct", "Admin", new { id = 8 }, new { @class = "product-create-link" })
                </li>
            </ul>
            <div data-tab="7" class="sub-header arrow-down">
                <div class="icon-container">
                    <img class="icon" src="~/Images/Admin/ram.png" alt="">
                </div>

                <div class="sub-header-2">
                    Ram
                    <i class="fas fa-angle-down"></i>
                </div>
            </div>

            <ul class="dropdown dropdown--7 ">
                <li>
                    @Html.ActionLink("Insert Ram", "InsertProduct", "Admin", new { id = 5 }, new { @class = "product-create-link" })
                </li>
            </ul>
            <div data-tab="2" class="sub-header arrow-down">
                <div class="icon-container">
                    <img class="icon" src="~/Images/Admin/cooler.png" alt="">
                </div>
                <div class="sub-header-2">
                    PSU
                    <i class="fas fa-angle-down"></i>
                </div>
            </div>
            <ul class="dropdown dropdown--2 ">
                <li>
                    @Html.ActionLink("Insert PSU", "InsertProduct", "Admin", new { id = 4 }, new { @class = "product-create-link" })
                </li>
            </ul>
            <div data-tab="3" class="sub-header arrow-down">
                <div class="icon-container">
                    <img class="icon" src="~/Images/Admin/motherboard.png" alt="">
                </div>
                <div class="sub-header-2">
                    Motherboard

                    <i class="fas fa-angle-down"></i>
                </div>
            </div>
            <ul class="dropdown dropdown--3 ">
                <li>
                    @Html.ActionLink("Insert Motherboard", "InsertProduct", "Admin", new { id = 1 }, new { @class = "product-create-link" })
                </li>
            </ul>
            <div data-tab="4" class="sub-header arrow-down">
                <div class="icon-container">
                    <img class="icon" src="~/Images/Admin/graphics.png" alt="">
                </div>
                <div class="sub-header-2">
                    GPU
                    <i class="fas fa-angle-down"></i>
                </div>
            </div>
            <ul class="dropdown dropdown--4">
                <li>
                    @Html.ActionLink("Insert GPU", "InsertProduct", "Admin", new { id = 3 }, new { @class = "product-create-link" })
                </li>
            </ul>
            <div data-tab="5" class="sub-header arrow-down">
                <div class="icon-container">
                    <img class="icon" src="~/Images/Admin/harddisk.png" alt="">
                </div>
                <div class="sub-header-2">
                    Hard Disc
                    <i class="fas fa-angle-down"></i>
                </div>
            </div>
            <ul class="dropdown dropdown--5 ">
                <li>
                    @Html.ActionLink("Insert Hard Disc", "InsertProduct", "Admin", new { id = 6 }, new { @class = "product-create-link" })
                </li>
            </ul>
            <div data-tab="6" class="sub-header arrow-down">
                <div class="icon-container">
                    <img class="icon" src="~/Images/Admin/cpu.png" alt="">
                </div>
                <div class="sub-header-2">
                    CPU
                    <i class="fas fa-angle-down"></i>
                </div>
            </div>
            <ul class="dropdown dropdown--6 ">
                <li>
                    @Html.ActionLink("Insert CPU", "InsertProduct", "Admin", new { id = 2 }, new { @class = "product-create-link" })
                </li>
            </ul>
            <ul>
                <li class="navigation-header-1">@Html.ActionLink("Products", "ViewAllProducts", "Admin", new { }, new { @class = "product-create-link" })</li>
                <li>
            </ul>
            <ul>
                <li class="navigation-header-2">@Html.ActionLink("Role Assign", "CreateRole", "Admin", new { }, new { @class = "product-create-link" })</li>

            </ul>
            s

        </div>

        <div class="page2-wrapper">
            <div class="admin-nav">
                <div class="admin-nav-end">
                    <img class="dark-light-mode-icon" src="~/Images/Icons/8665965_sun_icon.png" />
                    <img class="account-icon" src="~/Images/Other/face.jpg" />
                </div>
                <div class="admin-nav-dropdown-menu-container">
                    <div class="admin-nav-dropdown-header">
                        <img src="~/Images/Other/face.jpg" />
                        <div class="admin-nav-dropdown-header-1">
                            @if (Request.IsAuthenticated)
                            {

                <h4>
                    @HttpContext.Current.User.Identity.Name
                </h4>
                                <h6>
                                    @TempData["Username"]
                                </h6>}
                        </div>
                    </div>
                    <div class="admin-nav-dropdown-footer">
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("Logout", "User", FormMethod.Post, new { id = "logoutForm" }))
                            {
            <a href="javascript:document.getElementById('logoutForm').submit()">Sign out</a>}
                        }
                    </div>
                </div>
            </div>
            <button class="admin-sidebar-toggle">
                <i class="fas fa-angle-left"></i>
            </button>
            @RenderBody()
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/admin.js"></script>
</body>
</html>

Eshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CyberStore</title>
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/c93712fc6c.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
</head>
<body>
      <div class="email-sent-notification">
        <i class="fas fa-times remove-email-sent-notification"></i>
        <svg width="40" height="40" id="Layer_1" style="enable-background:new 0 0 30 30;" version="1.1" viewBox="0 0 30 30"
             xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <path fill="#5677fc"
              d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56  c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0  l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z" />
        </svg>
        <h4 class="email-sent-text">
            @if (TempData["emailSentNotification"] != null)
            {
                @TempData["emailSentNotification"].ToString()
            }
         </h4>
    </div>
    <button class="sidebar-toggle">
        <i class="fas fa-bars"></i>
    </button>
    <div class="navbar sidebar">
        <div class="navbar-container">
            <div class="links-container">
                <ul>
                    @if (this.User.IsInRole("Admin"))
                    {
                        <li class="ToAdminNaFenetaiMonoStousAdmins JJJ">@Html.ActionLink("Administrator", "Index", "Admin", new { }, new { @class = "nav-link" })</li>
                        { string username = User.Identity.Name; }
                    }
                    <li>@Html.ActionLink("Shop", "Products", "Home", new { }, new { @class = "nav-link" })</li>

                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Orders", "MyOrders", "Orders", new { }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Build your desktop", "YourDesktop", "Desktop", new { }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink(" Suggestions", "Suggestions", "Desktop", new { }, new { @class = "nav-link" })</li>
                    }
                    <li>@Html.ActionLink(" About us", "AboutUs", "Home", new { }, new { @class = "nav-link" })</li>

                </ul>
               

            </div>
            <div>
                <ul class="navbar-sub">
                    <li><a class="location-icon nav-link" target="_blank" href="https://www.google.com/maps/search/peoplecert/37.9801572,23.7322301,17z/data=!3m1!4b1">Store Locator</a></li>

                    @if (Request.IsAuthenticated)
                    {
                        <li>
                            @using (Html.BeginForm("Logout", "User", FormMethod.Post, new { id = "logoutForm" }))
                            {
                            <a style="font-size:12px" class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Logout : @HttpContext.Current.User.Identity.Name</a>
                            }
                        </li>
                    }

                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Login", "Login", "User", new { }, new { @class = "nav-link" })</li>

                    }
                
                </ul>
            </div>
        </div>
    </div>
    <section class="white-section">
        <div class="navbar-search-container">
            <div class="navbar-brand">
                <a href="~/"><img class="nav-logo" src="~/Images/Icons/navlogo.png" /></a>
            </div>
            <div class="search">
                <form class="search-form">
                    <input id="livesearchtags" name="livesearchtags" class="search-input" type="text" placeholder="Search for Product...">
                    @*<button class="search-form-btn" type="submit">
                        <img src="~/Images/search3.png" alt="">
                    </button>*@
                    <div id="result" class="tag-results"></div>
                </form>
               
                <div class="tooltip">
                    <a href="@Url.Action("WishList","Home")"> <i class="fa-regular fa-heart nav-heart"></i></a>
                    <span class="tooltiptext">
                        <h5>View Wishlist</h5>
                    </span>
                </div>
                <div class="cart-icon-container">
                    <a href="@Url.Action("Index", "Cart")"><img width="24" class="cart-icon" src="~/Images/Icons/cart-icon.png" alt=""></a>
                    <div class="cart-quantity">
                        <span id="items-to-cart">@TempData["productsInCart"]</span>
                    </div>
                </div>

            </div>
        </div>

        @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@

        @*@Html.Partial("_LoginPartial")*@

        <div class="body-content">
            @RenderBody()
        </div>
        <div class="footer">
            <div class="footer-container">
                <div class="links-container">
                    <h4>Shopping</h4>
                    @Html.ActionLink("Shop", "Products", "Home", new { }, new { @class = "" })
                </div>
                <div class="links-container">
                    <h4>Customer Service</h4>
                    @Html.ActionLink("My Account", "Login", "User", new { }, new { @class = "" })
                </div>
                <div class="links-container">
                    <h4>Quick Links</h4>
                    <a href="@Url.Action("Products", "Home", new { categoryId = 2 })">Cpu</a>
                    <a href="@Url.Action("Products", "Home", new { categoryId = 6 })">Hard Disks</a>
                    <a href="@Url.Action("Products", "Home", new { categoryId = 1 })">Motherboards</a>
                    <a href="@Url.Action("Products", "Home", new { categoryId = 5 })">Ram</a>
                </div>
                <div class="links-container newsletter-container">
                    <h4>Sign up to Newsletter</h4>
                    <div class="email-container">
                        <form method="post">
                            <input name="receiver" id="receiverEmail" class="email" type="email" placeholder="Your Email Adress..." />

                            <button type="submit" id="email-submit-btn" class="submit-email">
                                <img src="~/Images/Icons/email-arrow.png" alt="">
                            </button>
                            <p id="emailResult"></p>
                        </form>
                    </div>
                    <h6 class="gray">Stay up to date with all the actions that we are <br>saved for all our customers</h6>
                </div>
            </div>
            <div class="footer-container sub-footer">
                <p class="gray">2022 All Rights Reserved</p>
                <div>
                    <img src="~/Images/Icons/visa.png" alt="visa">
                    <img src="~/Images/Icons/mastercard.png" alt="mastercard">
                    <img src="~/Images/Icons/paypal.png" alt="paypal">
                    <img src="~/Images/Icons/western.png" alt="western">
                </div>
            </div>
            <div class="toast-container">
                <div class="toast-icon">
                    <i class="fas fa-paper-plane"></i>
                </div>
                <div class="toast-header">
                    <h3>Success</h3>
                    <p id="status"></p>
                </div>
            </div>
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/Scripts/AlternateNavbar.js"></script>
    <script src="~/Scripts/sendEmail.js"></script>
    <script>
        const emailText = document.querySelector('.email-sent-text');
        const emailNotify = document.querySelector('.email-sent-notification');

        if (emailText.innerText === "") {
        } else {
            emailNotify.classList.add('show-email-notification');
        }

        $('.remove-email-sent-notification').click(() => {
            $('.email-sent-notification').removeClass('show-email-notification');
        })
    </script>

</body>
</html>